# Homework 3 - NumPy

### NAME: Yijun Liang
### STUDENT ID: 3033099994

In [1]:
# Do not delete this cell.
import numpy as np

### Since we will run autograder on your notebook, for each question please do not reuse variable names that have been used in previous questions.

## NumPy Introduction

__1a) Create two numpy arrays called a and b where a should be all integers between 25-34 (inclusive), and b should be ten evenly spaced numbers between 1-6 (inclusive). Print a and b.__

In [10]:
a = np.arange(25, 35)
b = np.linspace(0,6,10)
print('a: ', a)
print('b: ', b)

a:  [25 26 27 28 29 30 31 32 33 34]
b:  [0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


__1b) Cube (i.e. raise to the power of 3) all the elements in both a and b (element-wise). Store the results in two new arrays called cubed_a and cubed_b. Print cubed_a and cubed_b.__

In [11]:
cubed_a = np.power(a, 3)
cubed_b = np.power(b, 3)
print('cubed_a: ', cubed_a)
print('cubed_b: ', cubed_b)

cubed_a:  [15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]
cubed_b:  [  0.           0.2962963    2.37037037   8.          18.96296296
  37.03703704  64.         101.62962963 151.7037037  216.        ]


__1c) Add the two cubed arrays (e.g., [1,2] + [3,4] = [4,6]) and store the result in an array called c. Print c.__

In [12]:
c = np.add(cubed_a, cubed_b)
print('c: ', c)

c:  [15625.         17576.2962963  19685.37037037 21960.
 24407.96296296 27037.03703704 29855.         32869.62962963
 36088.7037037  39520.        ]


__1d) Sum the elements with even indices of c and store the result in a variable called d. Print d.__

In [15]:
d = np.sum(c[1::2])
print('d: ', d)

d:  138962.96296296295


__1e) Take the element-wise square root of the c and store the result in an array called e. Print e.__

In [16]:
e = np.power(c, 0.5)
print('e: ', e)

e:  [125.         132.57562482 140.3045629  148.18906842 156.23048026
 164.42942874 172.7859948  181.29983351 189.97027058 198.79637824]


__1f) Append b to a, reshape the appended array so that it is a 4x5, 2d array and store the results in a variable called m. Print m.__


In [20]:
m = np.hstack([a, b]).reshape(4, 5)
print('m: ', m)

m:  [[25.         26.         27.         28.         29.        ]
 [30.         31.         32.         33.         34.        ]
 [ 0.          0.66666667  1.33333333  2.          2.66666667]
 [ 3.33333333  4.          4.66666667  5.33333333  6.        ]]


__1g) Extract the third and the fourth column of the m matrix. Store the resulting 4x2 matrix in a new variable called m2. Print m2.__


In [23]:
m2 = m[:,2:4]
print('m2: ', m2)

m2:  [[27.         28.        ]
 [32.         33.        ]
 [ 1.33333333  2.        ]
 [ 4.66666667  5.33333333]]


__1h) Take the dot product of m2 and m. Store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A$\cdot$B =A<sup>T</sup>B__

In [25]:
m3 = np.dot(np.transpose(m2), m)
print('m3: ', m3)

m3:  [[1650.55555556 1713.55555556 1776.55555556 1839.55555556 1902.55555556]
 [1707.77777778 1773.66666667 1839.55555556 1905.44444444 1971.33333333]]


__1i) Round the m3 matrix to three decimal points. Store the result in m4. Print m4.__


In [27]:
m4 = np.around(m3, decimals=3)
print('m4: ', m4)

m4:  [[1650.556 1713.556 1776.556 1839.556 1902.556]
 [1707.778 1773.667 1839.556 1905.444 1971.333]]


## NumPy and Masks
__2a) Create an array called f where the values are cosine(x) for x from 0 to pi with 50 equally spaced values (inclusive). Print f.__

In [28]:
f = np.linspace(1, np.pi, 50)
f = np.cos(f)
print('f: ', f)

f:  [ 0.54030231  0.50302074  0.46477845  0.42564848  0.38570556  0.34502598
  0.30368743  0.26176886  0.21935034  0.17651288  0.1333383   0.08990905
  0.04630809  0.00261868 -0.04107573 -0.08469169 -0.12814589 -0.17135535
 -0.21423754 -0.25671055 -0.29869327 -0.34010551 -0.38086818 -0.42090343
 -0.46013479 -0.49848734 -0.53588782 -0.57226481 -0.60754882 -0.64167247
 -0.67457058 -0.70618033 -0.73644134 -0.76529581 -0.79268864 -0.8185675
 -0.84288298 -0.86558863 -0.88664108 -0.90600013 -0.9236288  -0.93949343
 -0.95356371 -0.96581277 -0.97621722 -0.98475719 -0.99141635 -0.99618201
 -0.99904505 -1.        ]


__2b) Use a 'mask' to get an array that is True when f >= 1/2 and False when f < 1/2. Store the result in an array called g. Print g.__

In [30]:
g = f>=1/2
print('g: ', g)

g:  [ True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]


__2c) Create an array called h that has only those values where f>= 1/2. Print h.__

In [31]:
h = f[g]
print('h: ', h)

h:  [0.54030231 0.50302074]


## NumPy and 2 Variable Prediction

__Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x (number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [32]:
# seed the random number generator with a fixed value
# Do not delete this cell
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ', x)
print ('y = ', y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of x and the expected value of y. Store the results in two variables called ex and ey.__

In [33]:
ex = np.mean(x)
ey = np.mean(y)

__3b) Find variance of distributions of x and y. Store the results in two variables called varx and vary.__

In [34]:
varx = np.mean(x**2)
vary = np.mean(y**2)

__3c) Find co-variance of x and y. Store the result in a variable called cov.__

In [35]:
cov = np.mean(x*y) - ex*ey

__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
i.e. y_predicted = f(x) = y0 + kx. Store your predicitions in an array called y_pred. Print y_pred.__  

In [37]:
k = cov/vary
b = ey - cov/varx*ex
y_pred = b + k*x
y_pred

array([9.06870403, 9.0471316 , 9.08483353, 9.08839977, 9.07439272,
       9.09783332, 9.11156225, 9.11237166, 9.12157331, 9.13140319,
       9.16335884, 9.15280083, 9.15518707, 9.16606948, 9.17904748,
       9.21002342, 9.19691679, 9.19670301, 9.23627022, 9.22303638,
       9.23582604, 9.25154094, 9.26697064, 9.26634233, 9.27572218,
       9.29900141, 9.28932157, 9.30116178, 9.28118151, 9.32404814,
       9.33798233, 9.3288365 , 9.32541346, 9.34712488, 9.33823806,
       9.34872162, 9.3541708 , 9.36954704, 9.39823163, 9.4041014 ,
       9.41568345, 9.43682292, 9.44720097, 9.44961225, 9.42530866,
       9.4644717 , 9.46375437, 9.48070462, 9.46642859, 9.50487485,
       9.48454949, 9.49195578, 9.50953128, 9.53207682, 9.51136086,
       9.51733464, 9.56672971, 9.56253459, 9.58562453, 9.59310637,
       9.56320411, 9.60243124, 9.61174005, 9.60086575, 9.64055494,
       9.63016311, 9.62054384, 9.65673876, 9.66704966, 9.66972103,
       9.67755431, 9.69242949, 9.7097528 , 9.68797354, 9.72786

__3e) Put the prediction error into an array called y_error. Print y_error.__

In [38]:
y_error = y_pred - y
y_error

array([  7.40520284,   7.0256724 ,   6.976673  ,   6.82823482,
         7.11151714,   6.14236982,   6.08274338,   5.7767187 ,
         6.36691552,   5.70639249,   5.76665736,   5.75902316,
         5.37015364,   4.78313899,   4.84941162,   5.17077302,
         4.45999811,   4.89571902,   4.39463732,   4.44127682,
         4.23816817,   3.93407277,   3.49852393,   3.32910484,
         3.54760576,   2.58926526,   2.6078879 ,   2.72633447,
         2.10380548,   1.77541562,   2.03576814,   2.0085792 ,
         1.54517462,   1.43579122,   1.06169637,   0.6566888 ,
         0.57197216,   0.91057158,   0.50728448,   0.58690218,
         0.54461374,  -0.2251027 ,   0.04513848,  -0.41029557,
        -0.17828912,  -0.60939095,  -1.23204513,  -1.18651454,
        -1.71613426,  -1.06944351,  -1.98289767,  -1.45203339,
        -1.7549213 ,  -2.56547147,  -2.60851951,  -2.60422235,
        -2.60940722,  -2.87496734,  -3.4234992 ,  -3.27096557,
        -3.68320455,  -3.15876961,  -3.50549058,  -4.47

__3f) Write code that calculates the root mean square error (RMSE), that is root of average of y_error squared. Store the result in a variable called rmse. Print rmse.__

In [39]:
rmse = np.mean(y_error**2)
rmse

29.704578353454064

## Congratulations on completing hw3! Don't forget to click Kernel -> Restart & Run All, and submit this notebook on Gradescope.